-- Store the walk-forward quantile ladder beside each graded pick.
--
-- backfill_track_record already computes q10 through q90 from models refit on
-- seasons strictly before the one it scores, and then throws them away, keeping
-- only the median. That left the only honest quantiles in the system unstored,
-- so fit_interval_calibrator had to read the ladder from
-- player_projection_history instead -- which is generated by the ACTIVE model,
-- refit on every season including the ones being held out.
--
-- The difference is not academic. On the point prediction the same comparison
-- flipped the sign of the required correction: regressing outcome on prediction
-- gives a slope of 1.359 for pass_td in-sample and 0.531 walk-forward. A
-- correction fitted on the first stretches predictions that the second says
-- should be halved.
ALTER TABLE prop_edge_results ADD COLUMN IF NOT EXISTS q10 DOUBLE PRECISION;
ALTER TABLE prop_edge_results ADD COLUMN IF NOT EXISTS q25 DOUBLE PRECISION;
ALTER TABLE prop_edge_results ADD COLUMN IF NOT EXISTS q75 DOUBLE PRECISION;
ALTER TABLE prop_edge_results ADD COLUMN IF NOT EXISTS q90 DOUBLE PRECISION;
