CREATE TABLE player_game_stats (
    player_id TEXT,
    game_id TEXT,
    season INT,
    week INT,
    season_type TEXT,
    game_date DATE,
    opponent TEXT,
    team TEXT,
    position TEXT,
    position_group TEXT,

    passing_yards FLOAT,
    passing_tds FLOAT,
    passing_interceptions FLOAT,
    attempts FLOAT,
    completions FLOAT,
    passing_air_yards FLOAT,
    passing_yards_after_catch FLOAT,
    passing_first_downs FLOAT,
    passing_epa FLOAT,
    passing_cpoe FLOAT,

    rushing_yards FLOAT,
    rushing_tds FLOAT,
    carries FLOAT,
    rushing_first_downs FLOAT,
    rushing_epa FLOAT,
    rushing_fumbles FLOAT,
    rushing_fumbles_lost FLOAT,

    receiving_yards FLOAT,
    receiving_tds FLOAT,
    receptions FLOAT,
    targets FLOAT,
    receiving_air_yards FLOAT,
    receiving_yards_after_catch FLOAT,
    receiving_first_downs FLOAT,
    receiving_epa FLOAT,
    receiving_fumbles FLOAT,
    receiving_fumbles_lost FLOAT,
    target_share FLOAT,
    air_yards_share FLOAT,
    wopr FLOAT,
    racr FLOAT,

    def_tackles_solo FLOAT,
    def_tackles_with_assist FLOAT,
    def_tackle_assists FLOAT,
    def_tackles_for_loss FLOAT,
    def_tackles_for_loss_yards FLOAT,
    def_sacks FLOAT,
    def_sack_yards FLOAT,
    def_qb_hits FLOAT,
    def_interceptions FLOAT,
    def_interception_yards FLOAT,
    def_pass_defended FLOAT,
    def_tds FLOAT,
    def_fumbles FLOAT,
    def_fumbles_forced FLOAT,
    def_safeties FLOAT,

    fg_made FLOAT,
    fg_att FLOAT,
    fg_missed FLOAT,
    fg_blocked FLOAT,
    fg_long FLOAT,

    pat_made FLOAT,
    pat_att FLOAT,

    punt_returns FLOAT,
    punt_return_yards FLOAT,
    kickoff_returns FLOAT,
    kickoff_return_yards FLOAT,
    misc_yards FLOAT,

    PRIMARY KEY (player_id, game_id)
);
