SELECT 'nfl_players' AS tbl, COUNT(*) FROM nfl_players
UNION ALL SELECT 'nfl_games', COUNT(*) FROM nfl_games
UNION ALL SELECT 'player_game_stats', COUNT(*) FROM player_game_stats
UNION ALL SELECT 'snap_counts', COUNT(*) FROM snap_counts
UNION ALL SELECT 'ngs_passing', COUNT(*) FROM ngs_passing
UNION ALL SELECT 'ngs_receiving', COUNT(*) FROM ngs_receiving
UNION ALL SELECT 'ngs_rushing', COUNT(*) FROM ngs_rushing
UNION ALL SELECT 'pfr_adv_passing', COUNT(*) FROM pfr_adv_passing
UNION ALL SELECT 'pfr_adv_rushing', COUNT(*) FROM pfr_adv_rushing
UNION ALL SELECT 'pfr_adv_receiving', COUNT(*) FROM pfr_adv_receiving
UNION ALL SELECT 'pfr_adv_defense', COUNT(*) FROM pfr_adv_defense
UNION ALL SELECT 'ftn_charting_game', COUNT(*) FROM ftn_charting_game
UNION ALL SELECT 'participation_game', COUNT(*) FROM participation_game
UNION ALL SELECT 'pbp_player_game', COUNT(*) FROM pbp_player_game
UNION ALL SELECT 'ff_opportunity', COUNT(*) FROM ff_opportunity
UNION ALL SELECT 'depth_charts', COUNT(*) FROM depth_charts
UNION ALL SELECT 'rosters_weekly', COUNT(*) FROM rosters_weekly
UNION ALL SELECT 'injuries', COUNT(*) FROM injuries
UNION ALL SELECT 'player_id_crosswalk', COUNT(*) FROM player_id_crosswalk
ORDER BY 1;
