CREATE TABLE nfl_games (
    game_id TEXT PRIMARY KEY,
    season INT,
    week INT,
    game_type TEXT,
    game_date DATE,
    home_team TEXT,
    away_team TEXT,
    home_score INT,
    away_score INT,
    result INT,
    total FLOAT,
    spread_line FLOAT,
    total_line FLOAT,
    home_moneyline INT,
    away_moneyline INT,
    roof TEXT,
    surface TEXT,
    temp FLOAT,
    wind FLOAT,
    overtime INT,
    home_rest INT,
    away_rest INT,
    home_qb_name TEXT,
    away_qb_name TEXT,
    div_game INT
);
