docker exec -i player-prop-platform-postgres-1 psql -U app -d app <<'SQL'
CREATE TABLE IF NOT EXISTS player_game_feature_source (
  player_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  season INTEGER,
  week INTEGER,
  season_type TEXT,
  game_date DATE,
  team TEXT,
  opponent TEXT,
  position TEXT,
  position_group TEXT,

  -- base player stats
  passing_yards DOUBLE PRECISION,
  passing_tds DOUBLE PRECISION,
  passing_interceptions DOUBLE PRECISION,
  attempts DOUBLE PRECISION,
  completions DOUBLE PRECISION,
  passing_air_yards DOUBLE PRECISION,
  passing_yards_after_catch DOUBLE PRECISION,
  passing_first_downs DOUBLE PRECISION,
  rushing_yards DOUBLE PRECISION,
  rushing_tds DOUBLE PRECISION,
  carries DOUBLE PRECISION,
  rushing_first_downs DOUBLE PRECISION,
  receiving_yards DOUBLE PRECISION,
  receiving_tds DOUBLE PRECISION,
  receptions DOUBLE PRECISION,
  targets DOUBLE PRECISION,
  receiving_air_yards DOUBLE PRECISION,
  receiving_yards_after_catch DOUBLE PRECISION,
  def_tackles_solo DOUBLE PRECISION,
  def_sacks DOUBLE PRECISION,
  def_interceptions DOUBLE PRECISION,
  fg_made DOUBLE PRECISION,
  fg_att DOUBLE PRECISION,
  fg_long DOUBLE PRECISION,
  punt_return_yards DOUBLE PRECISION,
  kickoff_return_yards DOUBLE PRECISION,

  -- nfl_games context
  is_home INTEGER,
  home_team TEXT,
  away_team TEXT,
  home_score INTEGER,
  away_score INTEGER,
  game_result INTEGER,
  game_total DOUBLE PRECISION,
  spread_line DOUBLE PRECISION,
  total_line DOUBLE PRECISION,
  home_moneyline INTEGER,
  away_moneyline INTEGER,
  roof TEXT,
  surface TEXT,
  temp DOUBLE PRECISION,
  wind DOUBLE PRECISION,
  overtime INTEGER,
  home_rest INTEGER,
  away_rest INTEGER,
  rest_diff INTEGER,
  div_game INTEGER,
  home_qb_name TEXT,
  away_qb_name TEXT,

  -- pbp_player_game
  pbp_avg_air_yards_target DOUBLE PRECISION,
  pbp_avg_yac DOUBLE PRECISION,
  pbp_avg_epa_per_play DOUBLE PRECISION,
  pbp_avg_cp DOUBLE PRECISION,
  pbp_avg_cpoe DOUBLE PRECISION,
  pbp_red_zone_targets INTEGER,
  pbp_red_zone_target_rate DOUBLE PRECISION,
  pbp_red_zone_carries INTEGER,
  pbp_red_zone_carry_rate DOUBLE PRECISION,
  pbp_third_down_targets INTEGER,
  pbp_third_down_target_rate DOUBLE PRECISION,
  pbp_target_left_pct DOUBLE PRECISION,
  pbp_target_middle_pct DOUBLE PRECISION,
  pbp_target_right_pct DOUBLE PRECISION,
  pbp_run_left_pct DOUBLE PRECISION,
  pbp_run_middle_pct DOUBLE PRECISION,
  pbp_run_right_pct DOUBLE PRECISION,
  pbp_shotgun_pct DOUBLE PRECISION,
  pbp_avg_xyac DOUBLE PRECISION,
  pbp_avg_vegas_wp DOUBLE PRECISION,
  pbp_total_plays INTEGER,

  -- participation_game
  part_routes_run INTEGER,
  part_pass_snaps INTEGER,
  part_run_snaps INTEGER,
  part_shotgun_snaps INTEGER,
  part_shotgun_pct DOUBLE PRECISION,
  part_under_center_snaps INTEGER,
  part_under_center_pct DOUBLE PRECISION,
  part_man_coverage_snaps INTEGER,
  part_man_coverage_pct DOUBLE PRECISION,
  part_zone_coverage_snaps INTEGER,
  part_zone_coverage_pct DOUBLE PRECISION,
  part_avg_defenders_in_box DOUBLE PRECISION,
  part_avg_pass_rushers DOUBLE PRECISION,
  part_was_pressure_snaps INTEGER,
  part_was_pressure_pct DOUBLE PRECISION,

  -- snap_counts
  snap_team TEXT,
  snap_opponent TEXT,
  snap_position TEXT,
  offense_snaps DOUBLE PRECISION,
  offense_pct DOUBLE PRECISION,
  defense_snaps DOUBLE PRECISION,
  defense_pct DOUBLE PRECISION,
  st_snaps DOUBLE PRECISION,
  st_pct DOUBLE PRECISION,
  pfr_player_id TEXT,

  -- ftn_charting_game
  ftn_first_read_targets INTEGER,
  ftn_second_read_targets INTEGER,
  ftn_third_read_targets INTEGER,
  ftn_total_charted_targets INTEGER,
  ftn_first_read_target_rate DOUBLE PRECISION,
  ftn_play_action_snaps INTEGER,
  ftn_play_action_pct DOUBLE PRECISION,
  ftn_screen_pass_targets INTEGER,
  ftn_screen_pass_pct DOUBLE PRECISION,
  ftn_qb_out_of_pocket_snaps INTEGER,
  ftn_qb_out_of_pocket_pct DOUBLE PRECISION,
  ftn_motion_snaps INTEGER,
  ftn_motion_pct DOUBLE PRECISION,
  ftn_avg_blitzers_faced DOUBLE PRECISION,
  ftn_avg_box_defenders DOUBLE PRECISION,
  ftn_drops INTEGER,
  ftn_catchable_targets INTEGER,
  ftn_drop_rate DOUBLE PRECISION,
  ftn_contested_targets INTEGER,
  ftn_is_no_huddle_snaps INTEGER,

  -- ff_opportunity
  ffo_position TEXT,
  ffo_team TEXT,
  rec_yards_gained DOUBLE PRECISION,
  rec_yards_gained_exp DOUBLE PRECISION,
  rec_yards_gained_diff DOUBLE PRECISION,
  rush_yards_gained DOUBLE PRECISION,
  rush_yards_gained_exp DOUBLE PRECISION,
  rush_yards_gained_diff DOUBLE PRECISION,
  pass_yards_gained DOUBLE PRECISION,
  pass_yards_gained_exp DOUBLE PRECISION,
  pass_yards_gained_diff DOUBLE PRECISION,
  ffo_receptions DOUBLE PRECISION,
  receptions_exp DOUBLE PRECISION,
  receptions_diff DOUBLE PRECISION,
  rec_attempt DOUBLE PRECISION,
  rush_attempt DOUBLE PRECISION,
  pass_attempt DOUBLE PRECISION,
  rec_touchdown DOUBLE PRECISION,
  rec_touchdown_exp DOUBLE PRECISION,
  rush_touchdown DOUBLE PRECISION,
  rush_touchdown_exp DOUBLE PRECISION,
  total_fantasy_points DOUBLE PRECISION,
  total_fantasy_points_exp DOUBLE PRECISION,
  total_fantasy_points_diff DOUBLE PRECISION,

  -- ngs_passing
  ngs_pass_avg_time_to_throw DOUBLE PRECISION,
  ngs_pass_avg_completed_air_yards DOUBLE PRECISION,
  ngs_pass_avg_intended_air_yards DOUBLE PRECISION,
  ngs_pass_avg_air_yards_differential DOUBLE PRECISION,
  ngs_pass_aggressiveness DOUBLE PRECISION,
  ngs_pass_max_completed_air_distance DOUBLE PRECISION,
  ngs_pass_avg_air_yards_to_sticks DOUBLE PRECISION,
  ngs_pass_completion_percentage DOUBLE PRECISION,
  ngs_pass_expected_completion_percentage DOUBLE PRECISION,
  ngs_pass_completion_percentage_above_expectation DOUBLE PRECISION,
  ngs_pass_avg_air_distance DOUBLE PRECISION,
  ngs_pass_max_air_distance DOUBLE PRECISION,
  ngs_pass_passer_rating DOUBLE PRECISION,
  ngs_pass_attempts INTEGER,
  ngs_pass_completions INTEGER,
  ngs_pass_yards DOUBLE PRECISION,
  ngs_pass_touchdowns INTEGER,
  ngs_pass_interceptions INTEGER,

  -- ngs_rushing
  ngs_rush_efficiency DOUBLE PRECISION,
  ngs_rush_pct_gte_eight_defenders DOUBLE PRECISION,
  ngs_rush_avg_time_to_los DOUBLE PRECISION,
  ngs_rush_yards_over_expected DOUBLE PRECISION,
  ngs_rush_avg_rush_yards DOUBLE PRECISION,
  ngs_rush_yoe_per_att DOUBLE PRECISION,
  ngs_rush_pct_over_expected DOUBLE PRECISION,
  ngs_rush_expected_yards DOUBLE PRECISION,
  ngs_rush_attempts INTEGER,
  ngs_rush_yards DOUBLE PRECISION,
  ngs_rush_touchdowns INTEGER,

  -- ngs_receiving
  ngs_rec_avg_cushion DOUBLE PRECISION,
  ngs_rec_avg_separation DOUBLE PRECISION,
  ngs_rec_avg_intended_air_yards DOUBLE PRECISION,
  ngs_rec_pct_share_of_intended_air_yards DOUBLE PRECISION,
  ngs_rec_avg_yac DOUBLE PRECISION,
  ngs_rec_avg_expected_yac DOUBLE PRECISION,
  ngs_rec_avg_yac_above_expectation DOUBLE PRECISION,
  ngs_rec_catch_percentage DOUBLE PRECISION,
  ngs_rec_receptions INTEGER,
  ngs_rec_targets INTEGER,
  ngs_rec_yards DOUBLE PRECISION,
  ngs_rec_touchdowns INTEGER,

  -- pfr advanced
  pfr_pass_times_pressured DOUBLE PRECISION,
  pfr_pass_times_pressured_pct DOUBLE PRECISION,
  pfr_pass_times_blitzed DOUBLE PRECISION,
  pfr_pass_times_hit DOUBLE PRECISION,
  pfr_pass_times_hurried DOUBLE PRECISION,
  pfr_pass_times_sacked DOUBLE PRECISION,
  pfr_pass_drops DOUBLE PRECISION,
  pfr_pass_drop_pct DOUBLE PRECISION,
  pfr_pass_bad_throws DOUBLE PRECISION,
  pfr_pass_bad_throw_pct DOUBLE PRECISION,
  pfr_pass_def_times_blitzed DOUBLE PRECISION,
  pfr_pass_def_times_hitqb DOUBLE PRECISION,
  pfr_pass_def_times_hurried DOUBLE PRECISION,

  pfr_rush_carries DOUBLE PRECISION,
  pfr_rush_yards_before_contact DOUBLE PRECISION,
  pfr_rush_yards_before_contact_avg DOUBLE PRECISION,
  pfr_rush_yards_after_contact DOUBLE PRECISION,
  pfr_rush_yards_after_contact_avg DOUBLE PRECISION,
  pfr_rush_rushing_broken_tackles DOUBLE PRECISION,
  pfr_rush_receiving_broken_tackles DOUBLE PRECISION,

  pfr_rec_receiving_broken_tackles DOUBLE PRECISION,
  pfr_rec_receiving_drop DOUBLE PRECISION,
  pfr_rec_receiving_drop_pct DOUBLE PRECISION,
  pfr_rec_receiving_int DOUBLE PRECISION,
  pfr_rec_receiving_rat DOUBLE PRECISION,
  pfr_rec_rushing_broken_tackles DOUBLE PRECISION,
  pfr_rec_passing_drops DOUBLE PRECISION,
  pfr_rec_passing_drop_pct DOUBLE PRECISION,

  pfr_def_targets DOUBLE PRECISION,
  pfr_def_completions_allowed DOUBLE PRECISION,
  pfr_def_completion_pct DOUBLE PRECISION,
  pfr_def_yards_allowed DOUBLE PRECISION,
  pfr_def_yards_allowed_per_tgt DOUBLE PRECISION,
  pfr_def_yards_allowed_per_cmp DOUBLE PRECISION,
  pfr_def_air_yards_completed DOUBLE PRECISION,
  pfr_def_yards_after_catch DOUBLE PRECISION,
  pfr_def_adot DOUBLE PRECISION,
  pfr_def_ints DOUBLE PRECISION,
  pfr_def_receiving_td_allowed DOUBLE PRECISION,
  pfr_def_passer_rating_allowed DOUBLE PRECISION,
  pfr_def_sacks DOUBLE PRECISION,
  pfr_def_pressures DOUBLE PRECISION,
  pfr_def_missed_tackles DOUBLE PRECISION,
  pfr_def_missed_tackle_pct DOUBLE PRECISION,
  pfr_def_times_blitzed DOUBLE PRECISION,
  pfr_def_times_hitqb DOUBLE PRECISION,
  pfr_def_times_hurried DOUBLE PRECISION,
  pfr_def_tackles_combined DOUBLE PRECISION,

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (player_id, game_id)
);
SQL