ALTER TABLE prop_markets
ADD COLUMN IF NOT EXISTS scope TEXT,
ADD COLUMN IF NOT EXISTS target_kind TEXT,
ADD COLUMN IF NOT EXISTS entity_key TEXT,
ADD COLUMN IF NOT EXISTS eligible_positions TEXT[],
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS train_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS predict_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS feature_family TEXT,
ADD COLUMN IF NOT EXISTS upstream_dependency_codes TEXT[],
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS can_be_upstream_feature BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_synthetic_target BOOLEAN DEFAULT FALSE;
